services:
  html-vault:
    container_name: html-vault
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../db.sqlite3:/app/db.sqlite3:rw
    command: bundle e rake run
    ports:
      - "3000:80"
    env_file:
      - ../.env