services:
  html-vault:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../db.sqlite3:/app/db.sqlite3:rw
    command: ["bundle", "exec", "rake", "run"]
    networks:
      - proxt-net
